# PARADE prediction tutorial

In this tutorial, we will use PARADE predictor to estimate the activity of arbitrary sequences.

### Requirements

This code requires the following core Python modules:
* NumPy, Pandas
* PyTorch (preferably with CUDA support, if you have GPU)
* PyTorch Lightning (for PARADE wrappers)

In [1]:
import sys
import numpy as np
import pandas as pd

import torch
torch.cuda.is_available()

True

### Import PARADE modules

In [2]:
sys.path.append('../predictor/model/')
from predict import predict_sequences

Let's generate several random sequences to test the model.

The model was trained on 240nt long mRNA 3'UTR sequences (`T` stands for uracil).

The predictor yields reasonable assessments for sequences of similar length (~ 200-300nt), but with much shorter or longer 3'UTRs it is suggested to apply the predictor the the 5' region of the 3'UTR sequence.

In [3]:
def generate_random_sequences(n: int, length=240, alphabet=['A', 'T', 'G', 'C']):
    return [''.join(np.random.choice(alphabet, size=(length,), replace=True)) for _ in range(n)]

In [4]:
sequences = generate_random_sequences(10)
sequences

['GAGTATCTGAGGGGAACATGTGTATAGAACAGCCATTCCAAGAAGGCGCAAGGGCGCATGAGAAGGCACTTCCCGATTTGTAACGCCGGCCTGGCGTTTCCAGACGGAAGAGCTATCACACTCTGACAGTGCCAAAGTAACTCTATTTTACACGTTAAACTTCTCAAGCTGAGTTTCATCCATAGGCATTATGTCGAGGTCAGATAATAGGTTACTGCGCATGCCTGTTGGATTCGGCCC',
 'ATCTATTGTCCTCTACACCCGAATCCGTAAGTTGGGTCCGGAGCGCCTATACTTCATGATTTGGACCCCGTCAAATATTCTTCAGTAGTTACCGTCCAAAAGTGGCTTGCATCAGTGAAATTGGACGTGGACAATGTCCGCTCTTCGATCAGGTTTACAAATGGCCGATGGGCTCCCACCTGGGGACATGTAGTCAGTATTCACTTTGGCTCACTCGAGTCATTGAATTTAACCAACTTT',
 'CTCTCCGGCGCAATCTTTATAGTAATCTATAAAATAAACTCTGTAATCGCCGATCCCCGAAATCGTGATGCTGTATGGCGACATTCTGTCATGATCAGAAGCTACCATACTAGTACGTGGAAATTGCTGTATAGAAGGGACCGCATTCGGTATGGAGCAAAAAATCTATAGCGAACTGACTCATACCGGCCATATAACAGCTTTGACATTACATACTCTACAGATCCCGGGAGGCCGAGG',
 'CTGGTGGCCCTCCTCCATATGAAACACGTGAGAGGCCCAGTGCAGCGCGTATCATTTGCAGTACGTATATGCAACAAGGCTTTCGCGTCTGGGATGTCCGATTCAGTCTCCGTTGCGAGTTGTGCTGCTGCCCTATGGATGTCGCTAAGATAACTCGTCAGCTCGCCGCTTGAGAATGTAACTGCGATGCCAAAGTTTACCTGTTGACCACCGGTAGGGATACACGTCAACGCGACTAGC',
 'AGACTGACCGTTCACGCATTGCTCAAACGTCTGATCGAGGGTGTATGATGTGTCGTGTTTTGAGAACTCTGCTGGTGTTAGGAAAAACTCATCGGAGTATGTACGGGGGTCAAACGACACCTCGTGTGTGTACTCAGTTCTTAGCTTGTTTCGCCTGCATAACCGGGGTAGACGAATGCCTTCATACGTTAGCTTCAAGCAGAACGACTTATAGAAGGATGAATAACCGCGGTGGTTGAC',
 'CCAAGGATCAAGTGCTGCACGGTTGTAGCCTAGATCTGAGCATTTAGCTGTTCCTCCCGCCAAGACCACAAGGTGTCCATGGAGGTATTGGGTGCGGCTATGGGTCCAACCTGGTCTCCAACCTTGGGGGCAATATATGAAGCCTAGAGGGTTCGATATCTCTGGCGTCAGTGTGAATCCTCAAACCCACGCGGACGTCCTACATCCCCGTACTTTTTTGTAATCATGCCGGCATCGTTG',
 'GCAGATGTTGAAGAGCTCCTACCGACCAAAGTGACTTGATTTACAGCTTTTTTGATCGAACATGTGTGGTGCCAAGAGGGTTTTACAAAGCCCGGCTACCAAACTTCTCATAGTACTCCCATTCAGCCGGAAGAGGAGTAGTGGCGTGGACGCTCGGCCTGTCGGCTTCCTCATCTAATTGACGTAGTTATGCCCCCGTCACTCTCCTTGCTCGGACCACTCCGTTTCGAATCCAAAACA',
 'GTCCTCTTCACGCAGGCCTGAGGCACGCGACATTAGTGACTCGGAACAGGACTATACGCACTCGTCTTTTGTCCAGAATACGTTATCTTAACGACTTTGATTTTAAGTCTTCAGCAGGGGCGAACTAGGCCGCAACTAGGCACAGCTCCTCCGAGGTGCGTGGAGTGGTAGCTTCCTCGTACGCATTAGACGCGCAGTAGTCCCTGGCTTGAAAAATGCACCACTTCAAGAGTGTCGAAC',
 'AGCGAAGAGGTCCATGACGGGCTGCCCCTAGTATGCTATGAACCTACCCTCATAGTAATCAGCAACTGAAAATATGGCCTAACGACCGCATCTGAATCTATCTGGGGCGTCCCTAAGCCAAGACCGCACGCGAATGGGGCGGTGTCAAGCCAGCTCCGTCAGCAGGAGCGCTACGGAGGTACGAAGTGAAACGCGTATATGCCTCGATCTTTTGGCCCGAGAAAAAGCAGCTAACTGCGT',
 'AACTCGCATCACACTGGAGCAGATGACACAATGCGAAAGACGAGACCTACACAAAAAGTCGCCTACTCCATAAATGATCAGACGTTCGAAACGACTCATATAAAGCGTAAATCGTGTTGGCTGGGTCAGGGGCCCGATAGCGTAATGAATAGAAGCGCGATGACCGTGCGGTAGGGCAGCCGCCACCATTCGAGAGCTGGCTTGGGTAACCGTTGGTTTAGGCCGTTCTCCTCTGGACAT']

To predict the activity of an arbitrary sequence, pass it to the `predict_sequences` function.

Supply it only with the sequences of strictly equal length.

In [5]:
result = predict_sequences(sequences, utr_type='utr3', device='cpu')
result

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Predicting: 0it [00:00, ?it/s]

cell_type,c1,c13,c17,c2,c4,c6
seq,,,,,,
GAGTATCTGAGGGGAACATGTGTATAGAACAGCCATTCCAAGAAGGCGCAAGGGCGCATGAGAAGGCACTTCCCGATTTGTAACGCCGGCCTGGCGTTTCCAGACGGAAGAGCTATCACACTCTGACAGTGCCAAAGTAACTCTATTTTACACGTTAAACTTCTCAAGCTGAGTTTCATCCATAGGCATTATGTCGAGGTCAGATAATAGGTTACTGCGCATGCCTGTTGGATTCGGCCC,2.345155,2.428398,2.381866,2.356604,2.431392,2.394459
ATCTATTGTCCTCTACACCCGAATCCGTAAGTTGGGTCCGGAGCGCCTATACTTCATGATTTGGACCCCGTCAAATATTCTTCAGTAGTTACCGTCCAAAAGTGGCTTGCATCAGTGAAATTGGACGTGGACAATGTCCGCTCTTCGATCAGGTTTACAAATGGCCGATGGGCTCCCACCTGGGGACATGTAGTCAGTATTCACTTTGGCTCACTCGAGTCATTGAATTTAACCAACTTT,2.522944,2.576081,2.604536,2.623382,2.561562,2.662723
CTCTCCGGCGCAATCTTTATAGTAATCTATAAAATAAACTCTGTAATCGCCGATCCCCGAAATCGTGATGCTGTATGGCGACATTCTGTCATGATCAGAAGCTACCATACTAGTACGTGGAAATTGCTGTATAGAAGGGACCGCATTCGGTATGGAGCAAAAAATCTATAGCGAACTGACTCATACCGGCCATATAACAGCTTTGACATTACATACTCTACAGATCCCGGGAGGCCGAGG,2.455738,2.518806,2.466100,2.451491,2.492441,2.415232
CTGGTGGCCCTCCTCCATATGAAACACGTGAGAGGCCCAGTGCAGCGCGTATCATTTGCAGTACGTATATGCAACAAGGCTTTCGCGTCTGGGATGTCCGATTCAGTCTCCGTTGCGAGTTGTGCTGCTGCCCTATGGATGTCGCTAAGATAACTCGTCAGCTCGCCGCTTGAGAATGTAACTGCGATGCCAAAGTTTACCTGTTGACCACCGGTAGGGATACACGTCAACGCGACTAGC,2.313363,2.396911,2.285376,2.292614,2.389001,2.237197
AGACTGACCGTTCACGCATTGCTCAAACGTCTGATCGAGGGTGTATGATGTGTCGTGTTTTGAGAACTCTGCTGGTGTTAGGAAAAACTCATCGGAGTATGTACGGGGGTCAAACGACACCTCGTGTGTGTACTCAGTTCTTAGCTTGTTTCGCCTGCATAACCGGGGTAGACGAATGCCTTCATACGTTAGCTTCAAGCAGAACGACTTATAGAAGGATGAATAACCGCGGTGGTTGAC,2.374141,2.454717,2.376832,2.333080,2.414461,2.332607
CCAAGGATCAAGTGCTGCACGGTTGTAGCCTAGATCTGAGCATTTAGCTGTTCCTCCCGCCAAGACCACAAGGTGTCCATGGAGGTATTGGGTGCGGCTATGGGTCCAACCTGGTCTCCAACCTTGGGGGCAATATATGAAGCCTAGAGGGTTCGATATCTCTGGCGTCAGTGTGAATCCTCAAACCCACGCGGACGTCCTACATCCCCGTACTTTTTTGTAATCATGCCGGCATCGTTG,2.336905,2.410077,2.369880,2.369387,2.396943,2.424995
GCAGATGTTGAAGAGCTCCTACCGACCAAAGTGACTTGATTTACAGCTTTTTTGATCGAACATGTGTGGTGCCAAGAGGGTTTTACAAAGCCCGGCTACCAAACTTCTCATAGTACTCCCATTCAGCCGGAAGAGGAGTAGTGGCGTGGACGCTCGGCCTGTCGGCTTCCTCATCTAATTGACGTAGTTATGCCCCCGTCACTCTCCTTGCTCGGACCACTCCGTTTCGAATCCAAAACA,2.348882,2.490255,2.495831,2.471902,2.442228,2.396458
GTCCTCTTCACGCAGGCCTGAGGCACGCGACATTAGTGACTCGGAACAGGACTATACGCACTCGTCTTTTGTCCAGAATACGTTATCTTAACGACTTTGATTTTAAGTCTTCAGCAGGGGCGAACTAGGCCGCAACTAGGCACAGCTCCTCCGAGGTGCGTGGAGTGGTAGCTTCCTCGTACGCATTAGACGCGCAGTAGTCCCTGGCTTGAAAAATGCACCACTTCAAGAGTGTCGAAC,2.289530,2.520531,2.442825,2.428775,2.439467,2.407167
AGCGAAGAGGTCCATGACGGGCTGCCCCTAGTATGCTATGAACCTACCCTCATAGTAATCAGCAACTGAAAATATGGCCTAACGACCGCATCTGAATCTATCTGGGGCGTCCCTAAGCCAAGACCGCACGCGAATGGGGCGGTGTCAAGCCAGCTCCGTCAGCAGGAGCGCTACGGAGGTACGAAGTGAAACGCGTATATGCCTCGATCTTTTGGCCCGAGAAAAAGCAGCTAACTGCGT,2.214289,2.413021,2.374773,2.295517,2.441478,2.306962
AACTCGCATCACACTGGAGCAGATGACACAATGCGAAAGACGAGACCTACACAAAAAGTCGCCTACTCCATAAATGATCAGACGTTCGAAACGACTCATATAAAGCGTAAATCGTGTTGGCTGGGTCAGGGGCCCGATAGCGTAATGAATAGAAGCGCGATGACCGTGCGGTAGGGCAGCCGCCACCATTCGAGAGCTGGCTTGGGTAACCGTTGGTTTAGGCCGTTCTCCTCTGGACAT,2.219152,2.442322,2.317404,2.273340,2.367429,2.331402

To use a GPU, specify `device='cuda'`:

In [6]:
result = predict_sequences(sequences, utr_type='utr3', device='cuda')
result

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Predicting: 0it [00:00, ?it/s]

cell_type,c1,c13,c17,c2,c4,c6
seq,,,,,,
GAGTATCTGAGGGGAACATGTGTATAGAACAGCCATTCCAAGAAGGCGCAAGGGCGCATGAGAAGGCACTTCCCGATTTGTAACGCCGGCCTGGCGTTTCCAGACGGAAGAGCTATCACACTCTGACAGTGCCAAAGTAACTCTATTTTACACGTTAAACTTCTCAAGCTGAGTTTCATCCATAGGCATTATGTCGAGGTCAGATAATAGGTTACTGCGCATGCCTGTTGGATTCGGCCC,2.345155,2.428398,2.381866,2.356604,2.431392,2.394459
ATCTATTGTCCTCTACACCCGAATCCGTAAGTTGGGTCCGGAGCGCCTATACTTCATGATTTGGACCCCGTCAAATATTCTTCAGTAGTTACCGTCCAAAAGTGGCTTGCATCAGTGAAATTGGACGTGGACAATGTCCGCTCTTCGATCAGGTTTACAAATGGCCGATGGGCTCCCACCTGGGGACATGTAGTCAGTATTCACTTTGGCTCACTCGAGTCATTGAATTTAACCAACTTT,2.522944,2.576081,2.604536,2.623382,2.561562,2.662723
CTCTCCGGCGCAATCTTTATAGTAATCTATAAAATAAACTCTGTAATCGCCGATCCCCGAAATCGTGATGCTGTATGGCGACATTCTGTCATGATCAGAAGCTACCATACTAGTACGTGGAAATTGCTGTATAGAAGGGACCGCATTCGGTATGGAGCAAAAAATCTATAGCGAACTGACTCATACCGGCCATATAACAGCTTTGACATTACATACTCTACAGATCCCGGGAGGCCGAGG,2.455738,2.518806,2.466100,2.451491,2.492441,2.415232
CTGGTGGCCCTCCTCCATATGAAACACGTGAGAGGCCCAGTGCAGCGCGTATCATTTGCAGTACGTATATGCAACAAGGCTTTCGCGTCTGGGATGTCCGATTCAGTCTCCGTTGCGAGTTGTGCTGCTGCCCTATGGATGTCGCTAAGATAACTCGTCAGCTCGCCGCTTGAGAATGTAACTGCGATGCCAAAGTTTACCTGTTGACCACCGGTAGGGATACACGTCAACGCGACTAGC,2.313363,2.396911,2.285376,2.292614,2.389001,2.237197
AGACTGACCGTTCACGCATTGCTCAAACGTCTGATCGAGGGTGTATGATGTGTCGTGTTTTGAGAACTCTGCTGGTGTTAGGAAAAACTCATCGGAGTATGTACGGGGGTCAAACGACACCTCGTGTGTGTACTCAGTTCTTAGCTTGTTTCGCCTGCATAACCGGGGTAGACGAATGCCTTCATACGTTAGCTTCAAGCAGAACGACTTATAGAAGGATGAATAACCGCGGTGGTTGAC,2.374141,2.454717,2.376832,2.333080,2.414461,2.332607
CCAAGGATCAAGTGCTGCACGGTTGTAGCCTAGATCTGAGCATTTAGCTGTTCCTCCCGCCAAGACCACAAGGTGTCCATGGAGGTATTGGGTGCGGCTATGGGTCCAACCTGGTCTCCAACCTTGGGGGCAATATATGAAGCCTAGAGGGTTCGATATCTCTGGCGTCAGTGTGAATCCTCAAACCCACGCGGACGTCCTACATCCCCGTACTTTTTTGTAATCATGCCGGCATCGTTG,2.336905,2.410077,2.369880,2.369387,2.396943,2.424995
GCAGATGTTGAAGAGCTCCTACCGACCAAAGTGACTTGATTTACAGCTTTTTTGATCGAACATGTGTGGTGCCAAGAGGGTTTTACAAAGCCCGGCTACCAAACTTCTCATAGTACTCCCATTCAGCCGGAAGAGGAGTAGTGGCGTGGACGCTCGGCCTGTCGGCTTCCTCATCTAATTGACGTAGTTATGCCCCCGTCACTCTCCTTGCTCGGACCACTCCGTTTCGAATCCAAAACA,2.348882,2.490255,2.495831,2.471902,2.442228,2.396458
GTCCTCTTCACGCAGGCCTGAGGCACGCGACATTAGTGACTCGGAACAGGACTATACGCACTCGTCTTTTGTCCAGAATACGTTATCTTAACGACTTTGATTTTAAGTCTTCAGCAGGGGCGAACTAGGCCGCAACTAGGCACAGCTCCTCCGAGGTGCGTGGAGTGGTAGCTTCCTCGTACGCATTAGACGCGCAGTAGTCCCTGGCTTGAAAAATGCACCACTTCAAGAGTGTCGAAC,2.289530,2.520531,2.442825,2.428775,2.439467,2.407167
AGCGAAGAGGTCCATGACGGGCTGCCCCTAGTATGCTATGAACCTACCCTCATAGTAATCAGCAACTGAAAATATGGCCTAACGACCGCATCTGAATCTATCTGGGGCGTCCCTAAGCCAAGACCGCACGCGAATGGGGCGGTGTCAAGCCAGCTCCGTCAGCAGGAGCGCTACGGAGGTACGAAGTGAAACGCGTATATGCCTCGATCTTTTGGCCCGAGAAAAAGCAGCTAACTGCGT,2.214289,2.413021,2.374773,2.295517,2.441478,2.306962
AACTCGCATCACACTGGAGCAGATGACACAATGCGAAAGACGAGACCTACACAAAAAGTCGCCTACTCCATAAATGATCAGACGTTCGAAACGACTCATATAAAGCGTAAATCGTGTTGGCTGGGTCAGGGGCCCGATAGCGTAATGAATAGAAGCGCGATGACCGTGCGGTAGGGCAGCCGCCACCATTCGAGAGCTGGCTTGGGTAACCGTTGGTTTAGGCCGTTCTCCTCTGGACAT,2.219152,2.442322,2.317404,2.273340,2.367429,2.331402

A Pandas `DataFrame` object is returned. PARADE was trained to predict 3'UTR activities for 6 cell lines:
* MDA-MB-231 (`c1`)
* HepG2 (`c2`)
* Jurkat (`c4`)
* SW480 (`c6`)
* PA-1 (`c13`)
* NALM6 (`c17`)

You can also select particular cell lines for your query if you are doing a massive _in silico_ screening:

In [7]:
result = predict_sequences(sequences, utr_type='utr3', device='cpu', cell_line_codes=['c1', 'c6'])
result

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Predicting: 0it [00:00, ?it/s]

cell_type                                                 c1        c6
seq
GAGTATCTGAGGGGAACATGTGTATAGAACAGCCATTCCAAGAAGGC...  2.345196  2.394443
ATCTATTGTCCTCTACACCCGAATCCGTAAGTTGGGTCCGGAGCGCC...  2.522944  2.662736
CTCTCCGGCGCAATCTTTATAGTAATCTATAAAATAAACTCTGTAAT...  2.455778  2.415231
CTGGTGGCCCTCCTCCATATGAAACACGTGAGAGGCCCAGTGCAGCG...  2.313343  2.237216
AGACTGACCGTTCACGCATTGCTCAAACGTCTGATCGAGGGTGTATG...  2.374155  2.332625
CCAAGGATCAAGTGCTGCACGGTTGTAGCCTAGATCTGAGCATTTAG...  2.336878  2.425025
GCAGATGTTGAAGAGCTCCTACCGACCAAAGTGACTTGATTTACAGC...  2.348883  2.396489
GTCCTCTTCACGCAGGCCTGAGGCACGCGACATTAGTGACTCGGAAC...  2.289515  2.407174
AGCGAAGAGGTCCATGACGGGCTGCCCCTAGTATGCTATGAACCTAC...  2.214263  2.306976
AACTCGCATCACACTGGAGCAGATGACACAATGCGAAAGACGAGACC...  2.219153  2.331406

Save the result with Pandas

In [8]:
result.to_csv('scores_utr3.csv')