# PARADE prediction tutorial

In this tutorial, we will use PARADE predictor to estimate the activity of arbitrary sequences.

### Requirements

This code requires the following core Python modules:
* NumPy, Pandas
* PyTorch (preferably with CUDA support, if you have GPU)
* PyTorch Lightning (for PARADE wrappers)

In [1]:
import sys
import numpy as np
import pandas as pd

import torch
torch.cuda.is_available()

True

### Import PARADE modules

In [2]:
sys.path.append('../predictor/model/')
from predict import predict_sequences

Let's generate several random sequences to test the model.

The model was trained on 50nt long mRNA 5'UTR sequences (`T` stands for uracil).

If you have a longer sequence, it is recommended to use this predictor only for the 3'-end of your sequence.

In [3]:
def generate_random_sequences(n: int, length=50, alphabet=['A', 'T', 'G', 'C']):
    return [''.join(np.random.choice(alphabet, size=(length,), replace=True)) for _ in range(n)]

In [4]:
sequences = generate_random_sequences(10)
sequences

['TCCTCCTTAACACATCGAGACGGGGGGACGAAAAAGAAGCCCGCCGCGGT',
 'TGAAGCGTTATAGTTCCATCCTGTACATGAGCCAGCGCGTGTATCCTCCT',
 'TAGGGACGAACACGTGAATGACCGCCCAACCGAGCTGCTGACGACGGAAG',
 'ATATACCTGCTGCGGAATGATCGGGTCTGCGGCCCATACCGCTCATTTAT',
 'CGGACAAGCCAGATGGCGGGCAAGCGTATACGCTAGTGTGTCCTGAAAAG',
 'CGTTGGACCATTCGTATTCAACAGACATGCGACGATCACAAATTAAAGGG',
 'TGAAAATTGCTGGTATATTCTATCCTTAACCAGATTGATCGCCTGAGCCG',
 'ACGCCCGTACGTTTTATTAGCTGAAGAATAGCCATAGTGACCGGAGATGC',
 'CGCTGGAGATATGCTAAGGAAGGAGCTGCATTCTAGGGAGGCCTTTAGCC',
 'GAAAAGGGGTCCGGCGGCTTTGACGTTTAGTCGCGTCATACTGCCGCCTC']

To predict the activity of an arbitrary sequence, pass it to the `predict_sequences` function.

Supply it only with the sequences of strictly equal length.

In [5]:
result = predict_sequences(sequences, utr_type='utr5', device='cpu')
result

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Predicting: 0it [00:00, ?it/s]

cell_type,c1,c17,c2,c4,c6
seq,,,,,
TCCTCCTTAACACATCGAGACGGGGGGACGAAAAAGAAGCCCGCCGCGGT,2.564857,2.605461,2.561190,2.576632,2.570726
TGAAGCGTTATAGTTCCATCCTGTACATGAGCCAGCGCGTGTATCCTCCT,2.462410,2.519100,2.523204,2.459460,2.438857
TAGGGACGAACACGTGAATGACCGCCCAACCGAGCTGCTGACGACGGAAG,2.567847,2.504238,2.520137,2.485047,2.560872
ATATACCTGCTGCGGAATGATCGGGTCTGCGGCCCATACCGCTCATTTAT,2.292732,2.121620,2.329396,2.258776,2.224771
CGGACAAGCCAGATGGCGGGCAAGCGTATACGCTAGTGTGTCCTGAAAAG,2.369882,2.397910,2.402409,2.335808,2.313310
CGTTGGACCATTCGTATTCAACAGACATGCGACGATCACAAATTAAAGGG,2.333398,2.326770,2.383486,2.289678,2.288229
TGAAAATTGCTGGTATATTCTATCCTTAACCAGATTGATCGCCTGAGCCG,2.431226,2.446073,2.545872,2.444075,2.418103
ACGCCCGTACGTTTTATTAGCTGAAGAATAGCCATAGTGACCGGAGATGC,2.429410,2.319535,2.421933,2.308048,2.354378
CGCTGGAGATATGCTAAGGAAGGAGCTGCATTCTAGGGAGGCCTTTAGCC,2.204450,2.129556,2.232991,2.198537,2.174601
GAAAAGGGGTCCGGCGGCTTTGACGTTTAGTCGCGTCATACTGCCGCCTC,2.482044,2.436233,2.515009,2.410926,2.392648

To use a GPU, specify `device='cuda'`:

In [6]:
result = predict_sequences(sequences, utr_type='utr5', device='cuda')
result

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Predicting: 0it [00:00, ?it/s]

cell_type,c1,c17,c2,c4,c6
seq,,,,,
TCCTCCTTAACACATCGAGACGGGGGGACGAAAAAGAAGCCCGCCGCGGT,2.564857,2.605461,2.561190,2.576632,2.570726
TGAAGCGTTATAGTTCCATCCTGTACATGAGCCAGCGCGTGTATCCTCCT,2.462410,2.519100,2.523204,2.459460,2.438857
TAGGGACGAACACGTGAATGACCGCCCAACCGAGCTGCTGACGACGGAAG,2.567847,2.504238,2.520137,2.485047,2.560872
ATATACCTGCTGCGGAATGATCGGGTCTGCGGCCCATACCGCTCATTTAT,2.292732,2.121620,2.329396,2.258776,2.224771
CGGACAAGCCAGATGGCGGGCAAGCGTATACGCTAGTGTGTCCTGAAAAG,2.369882,2.397910,2.402409,2.335808,2.313310
CGTTGGACCATTCGTATTCAACAGACATGCGACGATCACAAATTAAAGGG,2.333398,2.326770,2.383486,2.289678,2.288229
TGAAAATTGCTGGTATATTCTATCCTTAACCAGATTGATCGCCTGAGCCG,2.431226,2.446073,2.545872,2.444075,2.418103
ACGCCCGTACGTTTTATTAGCTGAAGAATAGCCATAGTGACCGGAGATGC,2.429410,2.319535,2.421933,2.308048,2.354378
CGCTGGAGATATGCTAAGGAAGGAGCTGCATTCTAGGGAGGCCTTTAGCC,2.204450,2.129556,2.232991,2.198537,2.174601
GAAAAGGGGTCCGGCGGCTTTGACGTTTAGTCGCGTCATACTGCCGCCTC,2.482044,2.436233,2.515009,2.410926,2.392648

A Pandas `DataFrame` object is returned. PARADE was trained to predict 5'UTR activities for 5 cell lines:
* MDA-MB-231 (`c1`)
* HepG2 (`c2`)
* Jurkat (`c4`)
* SW480 (`c6`)
* NALM6 (`c17`)

You can also select particular cell lines for your query if you are doing a massive _in silico_ screening:

In [7]:
result = predict_sequences(sequences, utr_type='utr5', device='cpu', cell_line_codes=['c1', 'c6'])
result

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Predicting: 0it [00:00, ?it/s]

cell_type                                                 c1        c6
seq
TCCTCCTTAACACATCGAGACGGGGGGACGAAAAAGAAGCCCGCCGCGGT  2.564857  2.570719
TGAAGCGTTATAGTTCCATCCTGTACATGAGCCAGCGCGTGTATCCTCCT  2.462419  2.438859
TAGGGACGAACACGTGAATGACCGCCCAACCGAGCTGCTGACGACGGAAG  2.567851  2.560867
ATATACCTGCTGCGGAATGATCGGGTCTGCGGCCCATACCGCTCATTTAT  2.292741  2.224785
CGGACAAGCCAGATGGCGGGCAAGCGTATACGCTAGTGTGTCCTGAAAAG  2.369890  2.313310
CGTTGGACCATTCGTATTCAACAGACATGCGACGATCACAAATTAAAGGG  2.333389  2.288226
TGAAAATTGCTGGTATATTCTATCCTTAACCAGATTGATCGCCTGAGCCG  2.431226  2.418093
ACGCCCGTACGTTTTATTAGCTGAAGAATAGCCATAGTGACCGGAGATGC  2.429419  2.354389
CGCTGGAGATATGCTAAGGAAGGAGCTGCATTCTAGGGAGGCCTTTAGCC  2.204443  2.174625
GAAAAGGGGTCCGGCGGCTTTGACGTTTAGTCGCGTCATACTGCCGCCTC  2.482036  2.392646

Save the result with Pandas

In [8]:
result.to_csv('scores_utr5.csv')